GlobalNavigationの実装
siva-squad/squad-ui pull request #15
Opened 2023-10-31 01:33 UTC by nuintee

## 概要 / Overview

### Figmaのリンク / Figma Link

### Jira のチケット / Jira Ticket

## 変更内容 / Changes

## その他 / Other

2023-11-01 02:51 UTC, macfrei reviewed
I added a few comments, hope that is okay! 🙏

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/ListItemDropDown/ListItemDropDown.tsx
> +        data-ts-avoid-target={target}
I have never seen this before. What is it for? 🙂

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/ListItemDropDown/ListItemDropDown.stories.tsx
> +import { OTHERS_NAVIGATION } from "../MenuList/const";
Why is this in `/MenuList/const`? As far as I see it, it is only used for this story, so maybe we could couple it closer to this story?

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/ListItemDropDown/type.ts
> +}
Please remove this as it is not used 🙂

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.stories.tsx
> +  },
Since the default story doesn't render anything, how about removing it and adding the select type to the overall `argTypes`?
```suggestion
  argTypes: {
    navigationType: {
      type: "string",
      options: ["beyond", "connection", "account"],
      control: {
        type: "select",
      },
    },
  },
  decorators: [
    (Story) => (
      <div className="w-fit">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<typeof MenuList>;
```

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.tsx
> +      <div
Should this not maybe be a `nav` element?

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/MenuList/type.ts
> +export type MenuListType = "beyond" | "connection" | "account" | "";
Why can this be an empty string?

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.tsx
> +          nav.items.map((item) => {
For better readability, I usually prefer to filter before the return statement:
```suggestion
  ({ navigationType }, ref) => {
  
  const [menuNavigationItems] = MENU_NAVIGATION.filter((nav) => nav.groupId === navigationType)
  
    return (
      <div
        className="flex flex-col gap-y-4"
        ref={ref}
      >
        {menuNavigationItems.items.map((item) =>
```
I think when declaring and destructuring the items beforehand, the code becomes more readable. What do you think?

2023-11-01 02:51 UTC, macfrei commented on src/components/molecules/MenuList/type.ts
> +  absolute?: boolean;
Why are these types defined but not used by `MenuList`?

2023-11-01 02:51 UTC, macfrei commented on src/components/organisms/GlobalAccount/GlobalAccount.tsx
> +  onClick,
Why is the `onClick` optional?

2023-11-01 02:51 UTC, macfrei commented on src/components/organisms/GlobalNavigation/GlobalNavigation.tsx
> +          {items?.map((item, index) => (
Why is the optional chaining needed here? Isn't `items` always given?
```suggestion
          {items.map((item, index) => (
```

2023-11-01 02:51 UTC, macfrei commented on src/components/organisms/GlobalNavigation/hooks.ts
> +  );
Since the optional chaining is used here as well, I assume that `noCloseRefs` can be empty? What happens if the `noCloseRefs` is `null`? Could that be handled before going into the functions? 🤔

2023-11-01 02:51 UTC, macfrei commented on src/components/organisms/RichMenu/index.tsx
> +}: MenuListProps) => {
Why is the type `MenuListProps` and not `RichMenuProps`?

2023-11-01 03:25 UTC, nuintee commented on src/components/atoms/ListItem/ListItem.tsx
> +      isDangerText,
@macfrei 
Because red text `ListItem` was used in this file 
https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=2002-12571&mode=dev

I'm asking designers to add dangerText variant to the original `ListItem`👍

2023-11-01 03:28 UTC, nuintee commented on src/components/atoms/ListItem/ListItem.tsx
> +    const [localSelected, setLocalSelected] = useState(isSelected);
@macfrei 
Actually it wasn't needed 😂

I could've just used group-active: pseudo class to switch IconClassName

2023-11-01 03:33 UTC, nuintee commented on src/components/atoms/ListItem/const.ts
> +      large: "",
@macfrei 
This is to avoid weird  style overriding by `tv`.

Occasionally text regarding style is not working with `tv` somehow 🧐

That's why I had to style it explicitly.

2023-11-01 03:39 UTC, nuintee commented on src/components/molecules/ListItemDropDown/ListItemDropDown.tsx
> +        data-ts-avoid-target={target}
@macfrei 
This was just to avoid "not used variables" ESLint error 😅

I wanted pass `itemProp` prop directly to `ListItem` without getting ESLint errors, but the types don't match with `href`, and `target`.

So I used Destructuring assignment and Rest operator to pass props except those two to match the type.

But, I'll remove these `data-ts-*` and will pass props each by each 👍

2023-11-01 03:40 UTC, nuintee commented on src/components/molecules/ListItemDropDown/ListItemDropDown.stories.tsx
> +import { OTHERS_NAVIGATION } from "../MenuList/const";
@macfrei 
I'll move it closer 👍

2023-11-01 04:56 UTC, ogaru-sh commented
@nuintee 
２点コメントです！
### １点目
MenuListが表示されている段階で、今はMenuList以外の画面をクリックすれば閉じるようになっていると思いますが、画像の「Squad beyondチーム」（MenuListを開くために押したドロップダウン）を再クリックしたら閉じるという選択肢の追加も考えられるかなと思いました！
参考：[MUIのドロップダウン](https://mui.com/material-ui/react-select/)

<img width="2032" alt="スクリーンショット 2023-11-01 13 39 35" src="https://github.com/siva-squad/squad-ui/assets/48047855/18b9cbed-b086-4c6a-b9cc-f6d4e5fd2ae6">

### ２点目
今はStorybook上では画面縦幅が狭いと全体にスクロールバーYが出ていたので、MenuList自体にスクロールをつけるっていうのはありなんでしょうか？
（デザイン次第なところもあるだろうけど）

2023-11-01 06:06 UTC, yoheeeei requested changes
@nuintee 
以下2点お願いします！

1. package.jsonのversionを`0.3.0`に更新する
2. ↓に追加したコンポーネントをexportを追加する
- molecules/index.ts
 - organisms/index.ts

2023-11-01 06:13 UTC, nuintee commented on src/components/organisms/GlobalAccount/GlobalAccount.tsx
> +  onClick,
@macfrei 
Thanks! 
I'll make it required!

2023-11-01 06:14 UTC, nuintee commented on src/components/organisms/GlobalNavigation/GlobalNavigation.tsx
> +          {items?.map((item, index) => (
@macfrei 
Indeeed, I'll fix it!

2023-11-01 07:02 UTC, nuintee commented
> @nuintee ２点コメントです！
> 
> ### １点目
> MenuListが表示されている段階で、今はMenuList以外の画面をクリックすれば閉じるようになっていると思いますが、画像の「Squad beyondチーム」（MenuListを開くために押したドロップダウン）を再クリックしたら閉じるという選択肢の追加も考えられるかなと思いました！ 参考：[MUIのドロップダウン](https://mui.com/material-ui/react-select/)
> 
> <img alt="スクリーンショット 2023-11-01 13 39 35" width="2000" src="https://user-images.githubusercontent.com/48047855/279578507-18b9cbed-b086-4c6a-b9cc-f6d4e5fd2ae6.png">
> ### ２点目
> 今はStorybook上では画面縦幅が狭いと全体にスクロールバーYが出ていたので、MenuList自体にスクロールをつけるようにするって微妙そうですかね？（Storybookの仕様上の話？） <img alt="スクリーンショット 2023-11-01 13 39 35" width="2000" src="https://user-images.githubusercontent.com/48047855/279579916-c9e75327-6c09-4e09-bc22-7dbe1b5324b2.png">

@ogaru-sh 
ありがとうございます！

1. 対応します！

2. 恐らくStorybookの使用でのスクロールYですが、MeniList自体にスクロールを持たせようと思います！

2023-11-01 07:04 UTC, nuintee commented
> @nuintee 以下2点お願いします！
> 
> 1. package.jsonのversionを`0.3.0`に更新する
> 2. ↓に追加したコンポーネントをexportを追加する
> 
> * molecules/index.ts
> * organisms/index.ts

@yoheeeei 
ありがとうございます！
対応します！

2023-11-01 07:08 UTC, nuintee commented on src/components/molecules/MenuList/type.ts
> +export type MenuListType = "beyond" | "connection" | "account" | "";
@macfrei 
So that I can use "" (double quotation) as a default key value in `richMenuState`

2023-11-01 07:13 UTC, nuintee commented on src/components/molecules/MenuList/type.ts
> +  absolute?: boolean;
@macfrei 

Thank you, I'll recheck types again.

2023-11-01 07:14 UTC, nuintee commented on src/components/organisms/RichMenu/index.tsx
> +}: MenuListProps) => {
@macfrei 
Thank you, I'll recheck types again.

2023-11-01 07:29 UTC, macfrei commented on src/components/atoms/ListItem/const.ts
> +      large: "",
I see. I was just wondering because the color of the text is different when it is small or medium. I think maybe the text should always have the same color? Not sure what the design says though..

2023-11-01 07:31 UTC, macfrei commented on src/components/molecules/MenuList/type.ts
> +export type MenuListType = "beyond" | "connection" | "account" | "";
Could we be more specific and set it to `default` instead of double quotation? (Not sure if it would work though!)

2023-11-01 07:35 UTC, nuintee commented on src/components/organisms/GlobalNavigation/hooks.ts
> +  );
@macfrei 
I don't think I can handle it before going into the function...

Although, it's dealt inside `handleClickOutside` function at line 21. 
Maybe it's not enough?

I tried passing null to noCloseRef and the richMenu just didn't open, I think that's how it should be?

2023-11-01 07:38 UTC, macfrei commented on src/components/organisms/GlobalNavigation/hooks.ts
> +  );
If it doesn't work, don't worry. I am always a bit worried when I see optional chaining too much, but sometimes it can't be helped and that's alright too! 🙂 
So please don't worry if it is too much hassle and doesn't work 🙏 . And thank you for looking into it!!

2023-11-01 08:15 UTC, nuintee commented on src/components/atoms/ListItem/ListItem.tsx
> +    const [localSelected, setLocalSelected] = useState(isSelected);
@macfrei 

Oh, wait it's actually needed.
I added local state to track active state on Action component and switch icon Element depending on it's state which cannot be done by CSS

2023-11-01 08:17 UTC, nuintee commented on src/components/atoms/ListItem/const.ts
> +      large: "",
@macfrei 
Yes..,
text colors are different by size in the design.

2023-11-01 08:18 UTC, nuintee commented on src/components/organisms/GlobalNavigation/hooks.ts
> +  );
@macfrei 
Thank you!

2023-11-01 08:25 UTC, macfrei commented on src/components/atoms/ListItem/const.ts
> +      large: "",
Oh okay 😅, thanks for the clarification!

2023-11-01 10:06 UTC, nuintee commented on src/components/molecules/MenuList/MenuList.tsx
> +          nav.items.map((item) => {
@macfrei 
Looks Nice!

I'll fix this way.

2023-11-02 01:27 UTC, macfrei commented
@nuintee I have a meeting at 11, so the review might take some time! But I will try to be quick 🙇‍♀️ 
 11時から会議があるので、レビューには時間がかかるかもしれない！🙇‍♀️

2023-11-02 01:34 UTC, nuintee commented
> @nuintee I have a meeting at 11, so the review might take some time! But I will try to be quick 🙇‍♀️ 11時から会議があるので、レビューには時間がかかるかもしれない！🙇‍♀️

@macfrei 
Thank you! ☺️

2023-11-02 03:00 UTC, macfrei reviewed
I added a few more comments, ごめんなさい！ 🙇‍♀️

2023-11-02 03:10 UTC, macfrei commented
Oh and one more question. When you open the `GlobalNavigation` on the smartphone, should the navigation close when you touch outside of the navigation? I think I as a user would expect the navigation to close when the I would touch outside of the sidemenu. Is it understandable? 🙈 
![IMG_5586](https://github.com/siva-squad/squad-ui/assets/51355141/8504a1ed-4f8a-46da-a9d0-650ab9d7587b)

2023-11-02 05:29 UTC, nuintee commented on src/components/atoms/ListItem/const.ts
>        false: "",
@macfrei 
I think it's needed to use the variant in `compoundVariants`.

It has to be declared under `variants` I guess.

2023-11-02 05:31 UTC, nuintee commented on src/components/atoms/ListItem/const.ts
>        false: "",
@macfrei
I think it's needed to use the variant in compoundVariants.

It has to be declared under variants I guess.

2023-11-02 05:36 UTC, nuintee commented on src/hooks/useScreenSize.ts
> +  isSP: boolean;
@macfrei 
Yes, exactly.

Sounds good!

2023-11-02 06:13 UTC, nuintee commented
> Oh and one more question. When you open the `GlobalNavigation` on the smartphone, should the navigation close when you touch outside of the navigation? I think I as a user would expect the navigation to close when the I would touch outside of the sidemenu. Is it understandable? 🙈 ![IMG_5586](https://user-images.githubusercontent.com/51355141/279855052-8504a1ed-4f8a-46da-a9d0-650ab9d7587b.png)

@macfrei 
Thanks I'll fix it in this way.

2023-11-02 06:19 UTC, nuintee commented on src/hooks/useScreenSize.ts
> +  }, []);
@macfrei 
It's mainly used for 2 cases so far.

1. Responsive style implementation
hiding and showing components by media query for example.

2. used at RichMenu to calculate spaces between it self and window to implement scrolling to RichMenu which is absolute element.

2023-11-02 06:26 UTC, macfrei commented on src/hooks/useScreenSize.ts
> +  }, []);
Ah, I see, thank you! I didn't quite catch it in the `RichMenu` 🙏

2023-11-02 06:27 UTC, macfrei commented on src/components/atoms/ListItem/const.ts
>        false: "",
Ah, okay! Thank you :)

2023-11-02 07:54 UTC, nuintee commented
@macfrei 
I think I fixed all of the point outs, please check again 🙏

2023-11-02 08:19 UTC, macfrei commented on src/components/organisms/GlobalSidebar/hooks.ts
> +        onClose?.();
`onClose` will always be there, so no optional chaining in necessary 🙂 
```suggestion
        onClose();
```

2023-11-02 08:21 UTC, macfrei commented on src/components/organisms/GlobalSidebar/hooks.ts
> +      const isTrigger = triggerRef?.current?.contains(e.target as Node);
The second one is needed, the first one is not 🙂 
```suggestion
      const isTrigger = triggerRef.current?.contains(e.target as Node);
```

2023-11-02 08:22 UTC, macfrei commented on src/components/organisms/GlobalSidebar/index.tsx
> +  onClose?: () => void;
I doesn't really make sense to have it optional, don't you think?
```suggestion
  onClose: () => void;
```

2023-11-02 08:23 UTC, nuintee commented on src/components/organisms/GlobalSidebar/hooks.ts
> +      const isTrigger = triggerRef?.current?.contains(e.target as Node);
@macfrei 
Thanks!

2023-11-02 08:24 UTC, nuintee commented on src/components/organisms/GlobalSidebar/index.tsx
> +  onClose?: () => void;
@macfrei 
Done!

2023-11-02 08:24 UTC, nuintee commented on src/components/organisms/GlobalSidebar/hooks.ts
> +      const isTrigger = triggerRef?.current?.contains(e.target as Node);
@macfrei 
Done!

2023-11-02 08:25 UTC, nuintee commented on src/components/organisms/GlobalSidebar/hooks.ts
> +        onClose?.();
@macfrei 
Done!

2023-11-02 08:25 UTC, nuintee commented
@macfrei 
How about now?

2023-11-02 08:28 UTC, macfrei commented
@nuintee looks good, just the checks are not running through! Could you have a look? 🙇‍♀️

2023-11-02 08:30 UTC, nuintee commented
@macfrei 
> @nuintee looks good, just the checks are not running through! Could you have a look? 🙇‍♀️
I'll check why deploying to chromatic failed.

And For UI Review, UI Tests I'll ask the designers

2023-11-02 08:45 UTC, macfrei submitted a review, later dismissed
@nuintee looking good! Please get the approval of the designers before merging! おつかれさまでした！ 🙇‍♀️ 🙌 🚀

2023-11-02 09:03 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.tsx
> +MenuList.displayName = "MenuListSlot";
@nuintee I was wondering about that 🙂

2023-11-02 09:05 UTC, nuintee commented
> @nuintee looking good! Please get the approval of the designers before merging! おつかれさまでした！ 🙇‍♀️ 🙌 🚀

@macfrei 
Sorry for the back and forth...
And thanks a lot!

2023-11-06 04:31 UTC, nuintee commented
@macfrei @ogaru-sh 
Could you approve this PR again?

I already got approved by designers.

2023-11-06 04:34 UTC, macfrei approved these changes
LGTM 🚀

2023-11-06 04:40 UTC, merged