RichMenuの作成
siva-squad/squad-ui pull request #23
Opened 2023-11-08 03:27 UTC by nuintee

## 概要 / Overview
PR #20 をこちらに移行しました。
仕様漏れだったりコードの煩雑化があったので、
シンプルにする為別ブランチでリファクタリングしました。

## 変更点
- コードの整理・煩雑さ解消
- 仕様修正
  - MenuListItemホバー時にRichContentが出るように修正

### Figmaのリンク / Figma Link

### Jira のチケット / Jira Ticket

## 変更内容 / Changes

## その他 / Other

2023-11-08 08:10 UTC, yoheeeei submitted a review, later dismissed
LGTM 👍

2023-11-08 08:38 UTC, macfrei commented
@nuintee I will also still do a review, however, that will have to wait until tomorrow morning 😬

2023-11-09 03:10 UTC, macfrei requested changes
Please have a look at my comments 👍 

Also, in every other folder the convention of naming the files is to use the name of the component for example `MenuList.tsx` and then export it via `index.ts`. I would prefer it if it where the same everywhere, but it seems like it is not for `RichMenu` and `GlobalSidebar`. Could you adjust the naming? 🙂

2023-11-09 03:10 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.tsx
> +                onMouseLeave={() => onMouseLeave?.(item.id)}
Why are the functions optional here? As far as I understood, this component is only used in `RichMenu` which needs to use the `onMouseEnter`, in that case I would prefer for the prop not being optional and removing the optional chaining.

2023-11-09 03:10 UTC, macfrei commented on src/components/molecules/MenuList/MenuList.tsx
> +                {...(item as ListItemProps)}
Why is this casting (`(item as ListItemProps)`) needed?

2023-11-09 04:52 UTC, nuintee commented on src/components/molecules/RichMenuList/RichMenuList.tsx
> +        {groups?.map((group, index, passed) => (
I think there will be cases to be not given.

For example when there are no favorite folders or recently viewed folders yet. 

IMO,  I prefer to show `RichMenuList` even if the contents are empty, other wise users will not know RichMenuList exists until they view some folder or make them favorite.

2023-11-09 04:57 UTC, nuintee commented on src/components/organisms/RichMenu/RichMenuContents/index.tsx
> +  if (menuId === "default") return <></>;
@macfrei 

`default` is not in the design, but I'm using it as undefined menuId.

If I don't use `default` or some actual word, I have to add `""` in `MenuKindKey` enum type

2023-11-09 06:00 UTC, nuintee commented on src/components/molecules/MenuList/MenuList.tsx
> +                {...(item as ListItemProps)}
It's needed because I will get `size` and `href` type error regarding  conditional types.

Like so
```
Type '"small" | "large" | "medium" | undefined' is not assignable to type '"large" | undefined'.
```

2023-11-09 06:54 UTC, nuintee commented on src/components/atoms/ListItem/ListItem.tsx
> +        onMouseLeave={() => onMouseLeave?.(id || "")}
@macfrei 
Thanks! 
it was redundant.

I'll fix it!

2023-11-09 07:02 UTC, macfrei commented on src/components/organisms/RichMenu/RichMenuContents/index.tsx
> +  if (menuId === "default") return <></>;
Ah I see 👍

2023-11-09 07:24 UTC, nuintee commented on src/components/molecules/RichMenuList/RichMenuList.tsx
> +        {groups?.map((group, index, passed) => (
@nuintee 
I asked desinger for this
 and they said they will think of this but, maybe will go with showing the richMenuList event if it's empty.

So, I'll keep this way for now on 🧐

2023-11-09 07:38 UTC, nuintee commented
@macfrei 
How about now?

2023-11-09 07:50 UTC, macfrei commented on src/components/molecules/RichMenuList/RichMenuList.tsx
> +        {groups?.map((group, index, passed) => (
Okay 👍

2023-11-10 01:50 UTC, macfrei commented
@nuintee I will have a look 👍 
Also, @ogaru-sh should this component be moved to the `squadbeyond-frontend` after it has been merged or before?

2023-11-10 02:09 UTC, macfrei approved these changes
LGTM 👍

2023-11-10 02:26 UTC, merged