Feature/favorite button
siva-squad/squad-ui pull request #52
Opened 2023-12-14 13:29 UTC by macfrei

## 概要 / Overview

Added the favorite button atom which would be needed for the new design of the FolderListSidebar.
FolderListSidebarの新しいデザインに必要なお気に入りボタンatomを追加。

### package.jsonのversion

- [ ] 上げました

### Figmaのリンク / Figma Link

https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3544-25284&mode=design&t=ruus7LsFtdxWFPL3-0

2023-12-15 00:40 UTC, yoheeeei requested changes
@macfrei 
I found one typo, please fix it! 
Also, please update the version of package.json 👍

1点だけtypoを見つけたので修正をお願いします！
あとpackage.jsonのバージョンの更新もよろしくお願いします 👍

2023-12-15 00:40 UTC, yoheeeei commented on src/components/atoms/FavoriteButton/FavoriteButton.test.tsx
> +  test("has different label when isFavourite is true", async () => {
[nits]
typo
```suggestion
  test("has different label when isFavorite is true", async () => {
```

2023-12-15 05:34 UTC, macfrei commented on src/components/atoms/FavoriteButton/FavoriteButton.test.tsx
> +  test("has different label when isFavourite is true", async () => {
@yoheeeei thanks for checking! Sometimes it's really sad that British English and American English differs. In school I learned `favourite` but when coding, most people use American English like `favorite` or `color`. 😅 

確認してくれてありがとう！時々、イギリス英語とアメリカ英語の違いが本当に悲しい。学校では`favourite`って習ったけど、コーディングの時はほとんどの人が`favorite`とか`color`とかアメリカ英語を使う。😅

2023-12-15 08:02 UTC, yoheeeei commented on src/components/atoms/FavoriteButton/FavoriteButton.test.tsx
> +  test("has different label when isFavourite is true", async () => {
I see, there is such a difference 😲

2024-01-05 00:03 UTC, yoheeeei approved these changes
@macfrei 
細かい点を指摘しましたが概ね問題ありません、対応ありがとうございます！
LGTM 👍 
Approveしておくのでマージ前にパッケージのバージョン更新を忘れずに対応お願いします！

I pointed out a minor detail, but overall there are no problems. Thank you for your efforts!
LGTM 👍
I'll approve it, so please remember to update the package version before merging!

2024-01-05 00:03 UTC, yoheeeei commented on src/components/atoms/FavoriteButton/FavoriteButton.tsx
> +    : `${itemName}をお気に入りに追加`;
[nits]
日本語のみの対応になってしまうので多言語対応を考えるのであればpropsで渡せるようにした方が汎用的かもしれませんね
今対応しなくても問題なければ大丈夫です 👍 

[nits]
As it currently only supports Japanese, making it possible to pass languages through props might be more versatile for multilingual support. It's fine if this isn't addressed right now 👍

2024-01-05 01:09 UTC, macfrei commented on src/components/atoms/FavoriteButton/FavoriteButton.tsx
> +    : `${itemName}をお気に入りに追加`;
@yoheeeei thanks for the comment! That is true, especially since we are already introducing Taiwanese in the squadbeyond-frontend. I am thinking about adding an `ariaLabel` prop.

コメントありがとう！特にsquadbeyond-frontendではすでに台湾語を導入しているので、その通りです。ariaLabel`プロップを追加しようと考えています。

2024-01-05 02:07 UTC, macfrei commented on src/components/atoms/FavoriteButton/FavoriteButton.tsx
> +    : `${itemName}をお気に入りに追加`;
@yoheeeei if it looks good to you, could you please approve it once more? 🙂 

もしよろしければ、もう一度承認していただけますか？ 🙂

2024-01-05 02:08 UTC, yoheeeei commented on src/components/atoms/FavoriteButton/FavoriteButton.tsx
> +    : `${itemName}をお気に入りに追加`;
OK 👍👍👍

2024-01-05 02:08 UTC, yoheeeei approved these changes
LGTM 👍

2024-01-05 02:09 UTC, macfrei commented on src/components/atoms/FavoriteButton/FavoriteButton.tsx
> +    : `${itemName}をお気に入りに追加`;
ありがとう！ 🙌

2024-01-05 06:02 UTC, merged