Feat/combobox
siva-squad/squad-ui pull request #79
Opened 2024-02-13 03:44 UTC by macfrei

## 概要 / Overview

- Moved the `RequiredBadge` to Atoms so that it can be used again
- Added new icon under assets
- Created `Combobox` with keyboard accessibility

_日本語_:
- RequiredBadge`をAtomsに移動し、再び使用できるようにした。
- アセットの下に新しいアイコンを追加
- キーボードアクセシビリティを備えた `Combobox` を作成した。

### package.jsonのversion

- [ ] 上げました

### Figmaのリンク / Figma Link

https://www.figma.com/file/5KaykTqeXvtv3yGH9NV2Ol/Design-System?type=design&node-id=3899-5221&mode=design&t=4WlUFhEYmehCjFVT-0

2024-02-14 02:27 UTC, yoheeeei requested changes
@macfrei 
I made a few minor comments.
I think everything else is OK 👍

2024-02-14 02:27 UTC, yoheeeei commented on src/assets/icons/CheckIcon.tsx
> +        fill="#0091FF"
Setting it to `fill="currentColor"` allows the color to be changed from the parent 👍

`fill="currentColor"`にしておくと親から色の指定を変更できます 👍

2024-02-14 02:27 UTC, yoheeeei commented on src/components/atoms/RequiredBadge/index.ts
Please also add the export to `components/atoms/index.ts`!

`components/atoms/index.ts`へのexportの追加もよろしくお願いします！

2024-02-14 02:27 UTC, yoheeeei commented on src/components/molecules/Combobox/Combobox.stories.tsx
Please also add the export to `components/molecules/index.ts`!

2024-02-15 02:01 UTC, macfrei commented
@yoheeeei 
Thanks for the comments, I made the changes, please have a look again 🙇‍♀️ 
コメントありがとうございます、変更しました、もう一度見てください 🙇‍♀️

2024-02-15 03:40 UTC, yoheeeei approved these changes
@macfrei LGTM 👍

2024-02-15 04:54 UTC, merged